# Generated by Django 3.2 on 2023-11-29 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 4, 6, 53, 189135, tzinfo=utc)),
        ),
    ]
